config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import index, contacts, StudentDetailView, StudentListView, StudentCreateView, StudentUpdateView, \
    StudentDeleteView, toggle_activity

app_name = MainConfig.name

urlpatterns = [
    path('', index, name='index'),
    path('contacts/', contacts, name='contacts'),
    path('students/', StudentListView.as_view(), name='students_list'),
    path('student/<int:pk>/', StudentDetailView.as_view(), name='student_item'),
    path('students/create/', StudentCreateView.as_view(), name='students_create'),
    path('students/update/<int:pk>/', StudentUpdateView.as_view(), name='students_update'),
    path('students/delete/<int:pk>/', StudentDeleteView.as_view(), name='students_delete'),
    path('students/toggle/<int:pk>/', toggle_activity, name='toggle_activity'),
]

main/models.py
from django.db import models

#если поле необязательно для заполнения
NULLABLE = {'blank': True, 'null': True}

class Student(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='имя')
    last_name = models.CharField(max_length=150, verbose_name='фамилия')
    email = models.EmailField(max_length=150, unique=True, verbose_name='почта', **NULLABLE)

    avatar = models.ImageField(upload_to='students/', verbose_name='аватар', **NULLABLE)
    #в указанную папку будет складываться вся метаинформация из модели
    is_active = models.BooleanField(default=True, verbose_name='активный')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def delete(self, *args, **kwargs):
        self.is_active = False
        self.save()

    class Meta:
        verbose_name = 'студент'
        verbose_name_plural = 'студенты'
        ordering = ('last_name',)


class Subject(models.Model):
    title = models.CharField(max_length=150, verbose_name='название')
    description = models.TextField(verbose_name='описание')

    student = models.ForeignKey(Student, on_delete=models.CASCADE, verbose_name='студент')

    def __str__(self):
        return f'{self.title} ({self.student})'

    class Meta:
        verbose_name = 'предмет'
        verbose_name_plural = 'предметы'

main/forms.py
from django import forms

from main.models import Student, Subject


class FormStyleMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for fild_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class StudentForm(FormStyleMixin, forms.ModelForm):


    class Meta:
        model = Student
        # fields = '__all__'
        fields = ('first_name', 'last_name', 'email')
        # exclude = ('is_active',)

    def clean_email(self):
        cleaned_data = self.cleaned_data['email']

        if '@sky.pro' not in cleaned_data:
            raise forms.ValidationError('Почта должна быть от учебного заведения')

        return cleaned_data



class SubjectForm(FormStyleMixin, forms.ModelForm):


    class Meta:
        model = Subject
        fields = '__all__'

main/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic

from main.forms import StudentForm, SubjectForm
from main.models import Student, Subject
from main.servises import send_deactivate_email


def index(request):
    context = {
        'object_list': Student.objects.all()[:3],
        'title': 'Главная'
    }
    return render(request, 'main/index.html', context)


class StudentListView(generic.ListView):
    model = Student
    extra_context = {
        'title': 'Список студентов'
    }
    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_active=True)
        return queryset


class StudentDetailView(generic.DetailView):
    model = Student

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        #  #то же самое
        # context_data['title'] = self.get_object()
        return context_data


class StudentCreateView(generic.CreateView):
    model = Student
    # fields = ('first_name', 'last_name',)
    form_class = StudentForm
    success_url = reverse_lazy('main:students_list')




class StudentUpdateView(generic.UpdateView):
    model = Student
    # fields = ('first_name', 'last_name',)
    form_class = StudentForm
    template_name = 'main/student_form_with_formset.html'
    # success_url = reverse_lazy('main:students_list')

    def get_success_url(self, *args, **kwargs):
        return reverse('main:students_update', args=[self.get_object().pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        SubjectFormset = inlineformset_factory(Student, Subject, form=SubjectForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = SubjectFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = SubjectFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

class StudentDeleteView(generic.DeleteView):
    model = Student
    success_url = reverse_lazy('main:students_list')


def toggle_activity(request, pk):
    student_item = get_object_or_404(Student, pk=pk)
    if student_item.is_active:
        student_item.is_active = False
        # send_deactivate_email(student_item)
    else:
        student_item.is_active = True

    student_item.save()

    return redirect(reverse('main:student_item', args=[student_item.pk]))

def contacts(request):
    '''контроллер'''
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        message = request.POST.get('message')
        print(f'User {name} with email {email} send message: {message}')

    context = {
        'title': 'Контакты'
    }

    return render(request, 'main/contact.html', context)

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <style>
        main {
            margin-top: 150px;
        }
    </style>
</head>
<body>
<div class="container marketing">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Carousel</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                        aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    {% include 'main/includes/inc_main_menu.html' %}
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>

    <main>
        <!-- Three columns of text below the carousel -->
        <h1>{{ title }}</h1>
        <div class="row">
            {% block content %}
            {% endblock %}
        </div><!-- /.row -->
    </main>
</div>
</body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-1"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Hi, Sky!</h3>
            </div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <input class="form-control" placeholder="name" name="name"/><br><br>
                    <input class="form-control" placeholder="email" name="email" type=”email”/><br><br>
                    <textarea class="form-control" placeholder="your message" name="message"></textarea><br><br>
                    <input class="btn btn-primary" type="submit" value="Submit"/>
                </form>
            </div>
        </div>
    </div>
    <div class="col-4">
        <p>Moscow</p>
        <p>Istanbul</p>
        <p>Qatar</p>
    </div>
{% endblock %}

main/templates/main/includes/inc_main_menu.html
<ul class="navbar-nav me-auto mb-2 mb-md-0">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">Главная</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'main:students_list' %}">Все студенты</a>
    </li>
    <li class="nav-item">
    <a class="nav-link" href="{% url 'main:contacts' %}">Контакты</a>
    </li>
</ul>

main/templates/main/includes/inc_student_card.html
<div class="col-lg-4">
    <div class="card m-2 text-center">
        <div class="card-body">
            <svg class="bd-placeholder-img rounded-circle" width="140" height="140"
                 xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 140x140"
                 preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title>
                <rect width="100%" height="100%" fill="#777"/>
                <text x="50%" y="50%" fill="#777" dy=".3em">140x140</text>
            </svg>
            <h2>{{ object.first_name|title }} {{ object.last_name|title }}</h2>
            <p><a class="btn btn-secondary" href="{% url 'main:student_item' object.pk %}" role="button">Посмотреть &raquo;</a></p>
            <p><a class="btn btn-warning" href="{% url 'main:students_update' object.pk %}" role="button">Изменить &raquo;</a></p>
            <p><a class="btn btn-danger" href="{% url 'main:students_delete' object.pk %}" role="button">Удалить &raquo;</a></p>
        </div>
    </div>
</div><!-- /.col-lg-4 -->

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}
    {% for object in object_list %}
        {% include 'main/includes/inc_student_card.html' %}
    {% endfor %}
{% endblock %}

main/templates/main/student_confirm_delete.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    Уверены, что хотите удалить студента "{{ object }}"?<br>
                    <input type="submit" class="btn btn-outline-danger" value="Уверен">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:students_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_detail.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <tr>
                        <td>Имя</td>
                        <td>{{ object.first_name }}</td>
                    </tr>
                    <tr>
                        <td>Фамилия</td>
                        <td>{{ object.last_name }}</td>
                    </tr>
                </table>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:students_list' %}" class="btn btn-primary"><< Назад</a>
                <a href="{% url 'main:toggle_activity' object.pk %}" class="btn btn-outline-warning float-right">
                    {% if object.is_active %}
                    Деактивировать
                    {% else %}
                    Активировать
                    {% endif %}
                </a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_form.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col">
        <div class="card">
            <div class="card-body">
                <form method="post>">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-success" value="Создать">
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'main:students_list' %}" class="btn btn-primary"><< Назад</a>
            </div>
        </div>
    </div>
{% endblock %}

main/templates/main/student_form_with_formset.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col">
        <form class="row" method="post">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-success"
                               value="{% if object %}Сохранить{% else %}Создать{% endif %}">

                    </div>
                    <div class="card-footer">
                        <a href="{% url 'main:students_list' %}" class="btn btn-primary"><< Назад</a>
                    </div>
                </div>
            </div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">Предметы</div>
                    <div class="card-body">
                        <table class="table">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                <tr class="subject-form">
                                    <td>{{ form.as_p }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

main/templates/main/student_list.html
{% extends 'main/base.html' %}

{% block content %}
    <div class="col-12">
        <a href="{% url 'main:students_create' %}" class="btn btn-primary m-2">Создать студента</a>
    </div>
    {% for object in object_list %}
        {% include 'main/includes/inc_student_card.html' %}
    {% endfor %}
{% endblock %}
{% block footer %}
    <div class="row mb-5">
        <div class="col-12">
            (c) Alexey
        </div>
    </div>
{% endblock %}